import type { Meta, StoryObj } from "@storybook/react";

import { AllTradesGroup } from "@/components";

const meta = {
  title: "Components/AllTradesGroup",
  component: AllTradesGroup,
  parameters: {
    layout: "fullscreen",
  },

  tags: ["autodocs"],

  argTypes: {},
} satisfies Meta<typeof AllTradesGroup>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Primary: Story = {
  args: {
    isLoading: false,
    politicianTrades: [
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Sell",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Sell",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Buy",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Sell",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Sell",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Exchange",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Sell",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Buy",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Sell",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Exchange",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Sell",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
      {
        politicianName: "Nancy Peloci",
        imageUrl: "https://www.congress.gov/img/member/p000197_200.jpg",
        chamber: "Senate",
        politicalParty: "Democrat",
        stateAbv: "CA",
        issuerName: "Us Tax Payer",
        issuerDetail: "",
        transactionType: "Buy",
        buyDayMonth: "5 Jan",
        buyYear: "2024",
        reportedDayMonth: "8 Jan",
        reportedYear: "2024",
        timeTookToReport: "14",
        owner: "Spouse",
        size: "150k-200k",
        price: "300k",
      },
    ],
  },
};
