import { PoliticianCardProps } from "@/components";

export const defaultIssuers: string[] = [
  "Company 1",
  "Company 2",
  "Company 3",
  "Company 4",
  "Company 5",
  "Company 6",
  "Company 7",
  "Company 8",
  "Company 9",
  "Company 10",
];

export const mockPolititicans: PoliticianCardProps[] = [
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
  {
    politicianImage: "",
    politicianName: "Nancy Peloci",
    tradeVolume: "1.5M",
    numOfTrades: "46",
    lastTradeDate: "12/22/2023",
    chamber: "House",
    state: "CA",
    politicalParty: "Democratic",
    href: "",
    politicianId: "",
  },
];

export const politicalParties = ["Republican", "Democrat", "Other"];

export const states: string[] = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
];

export const allCommittees: string[] = [
  "Agriculture",
  "Agriculture, Nutrition, and Forestry",
  "Appropriations",
  "Armed Services",
  "Banking, Housing, and Urban Affairs",
  "Budget",
  "Commerce, Science, and Transportation",
  "Education and Labor",
  "Energy and Commerce",
  "Energy and Natural Resources",
  "Environment and Public Works",
  "Ethics",
  "Finance",
  "Financial Services",
  "Foreign Affairs",
  "Foreign Relations",
  "Health, Education, Labor, and Pensions",
  "Homeland Security",
  "Homeland Security and Governmental Affairs",
  "House Administration",
  "Indian Affairs",
  "Joint Committee on Printing",
  "Joint Committee on Taxation",
  "Joint Committee on the Library",
  "Joint Economic Committee",
  "Judiciary",
  "Natural Resources",
  "Oversight and Reform",
  "Rules",
  "Rules and Administration",
  "Science, Space, and Technology",
  "Select Committee on Ethics",
  "Select Committee on Intelligence",
  "Small Business",
  "Small Business and Entrepreneurship",
  "Transportation and Infrastructure",
  "Veterans' Affairs",
  "Ways and Means",
];
export const timePeriodOptions: string[] = [
  "30 Days",
  "90 Days",
  "180 Days",
  "1 Year",
  "3 Year",
];
